---
- hosts: masters
  become: true
  vars_files:
    - env_variables
  tasks:
    - name: Pulling images required for seeting up a Kubernetes cluster
      command: |
        kubeadm config images pull
      register: pull_images
      changed_when: false
    - name: Resetting the cluster
      command: |
        kubeadm reset -f
      register: reset_cluster
      changed_when: false

    # https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/
    - name: Initializing the cluster
      command: |
        kubeadm init --apiserver-advertise-address={{ ad_addr }} --apiserver-bind-port 6443 --pod-network-cidr={{ cidr_v }} --skip-phases=addon/kube-proxy
      register: init_cluster
      changed_when: false

    # https://www.maths.cam.ac.uk/computing/linux/unixinfo/perms#:~:text=644%20means%20you%20can%20read,users%20can%20only%20read%20it.
    - name: Storing Logs and Generated token for future purpose
      copy: content={{ init_cluster.stdout }} dest={{ token_file }} mode=0644
      delegate_to: localhost
      become: false

    - name: Copying required files
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      changed_when: false
      tags: skip_ansible_lint

    - name: Enable kubectl autocompletion
      shell: |
        echo 'source <(kubectl completion bash)' >>~/.bashrc
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -F __start_kubectl k' >>~/.bashrc
      changed_when: false
      become: false

    - name: Add Helm repository
      block:
        - name: Get key
          ansible.builtin.get_url:
            url: https://baltocdn.com/helm/signing.asc
            dest: /tmp/helm_key
        - name: Install key
          ansible.builtin.apt_key:
            file: /tmp/helm_key
            state: present
        - name: Convert key to gpg
          ansible.builtin.shell: |
            set -o pipefail
            cat /tmp/helm_key | gpg --dearmor > /usr/share/keyrings/helm.gpg
          changed_when: false
        - name: Add repository file
          ansible.builtin.apt_repository:
            filename: helm-stable.list
            repo: deb [signed-by=/usr/share/keyrings/helm.gpg] http://baltocdn.com/helm/stable/debian/ all main
            state: present
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600
    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present
    - name: Add cilium repository
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: http://helm.cilium.io/
        state: present
    - name: Install cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        release_name: cilium
        state: present
        wait: true
        timeout: 300
        values:
          global:
            operator:
              nodeinit:
                enabled: true
              enabled: true
            k8sServiceHost: "{{ ad_addr }}"
            k8sServicePort: 6443
          cilium:
            tunnel: vxlan
            k8sServiceHost: "{{ ad_addr }}"
            k8sServicePort: 6443
            enableBPF: true
            ipam: kubernetes
            k8sClusterName: kubernetes
            k8sServiceAccount: cilium
            k8sClusterLabels: {}
            k8sPrometheusMetrics: true
            k8sPrometheusMetricsPort: 9090
            k8sPrometheusMetricsPath: /metrics
            k8sPolicy:
              ## Enable Kubernetes NetworkPolicy support
              enabled: true
              ## Enable host isolation mode
              ## Requires Cilium to be run in privileged mode
              ## Requires Cilium to be run as a DaemonSet
              ## Requires Cilium to be run with the hostNetwork setting enabled
              ## Requires Cilium to be run with the hostPID setting enabled
              ## Requires Cilium to be run with the hostIPC setting enabled
              ## Requires Cilium to be run with the privileged setting enabled
              ## Requires Cilium to be run with the net_admin capability
              ## Requires Cilium to be run with the sys_admin capability
              ## Requires Cilium to be run with the sys_module capability
              ## Requires Cilium to be run with the dac_read_search capability
              ## Requires Cilium to be run with the dac_override capability
              ## Requires Cilium to be run with the audit_write capability
              ## Requires Cilium to be run with the chown capability
              ## Requires Cilium to be run with the fowner capability
              ## Requires Cilium to be run with the fsetid capability
              ## Requires Cilium to be run with the kill capability
              ## Requires Cilium to be run with the setgid capability
              ## Requires Cilium to be run with the setuid
    - name: Check Cilium CLI exists
      ansible.builtin.stat:
        path: /usr/local/bin/cilium
      register: cilium_cli_exists
      changed_when: false
    - name: Install Cilium CLI
      ansible.builtin.shell: |
        set -o pipefail
        CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
        GOOS=$(go env GOOS)
        GOARCH=$(go env GOARCH)
        curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
        sha256sum --check cilium-${GOOS}-${GOARCH}.tar.gz.sha256sum
        sudo tar -C /usr/local/bin -xzvf cilium-${GOOS}-${GOARCH}.tar.gz
        rm cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
      become: true
      when: not cilium_cli_exists.stat.exists
      changed_when: not cilium_cli_exists.stat.exists
