# ITNOA

- name: show write custom value based on host in each host
  hosts: all
  tasks:
    - name: show write custom value based on host in each host
#      command: echo "{{hostvars['{{inventory_hostname}}']['custom_var']}}"
      shell: > 
        echo "{{ hostvars[inventory_hostname]['ss'] }}aa" | tee /tmp/host_var.txt
#        echo "{{ hostvars[item]['ss'] }}" | tee /tmp/host_var.txt
#      when: ansible_hostname == "item"
#      with_items:
#        - "{{ groups['workers'] }}"
    - debug:
#        msg: "{{hostvars['{{inventory_hostname}}']}}"
        msg: "{{inventory_hostname}}"
  